uk:
  buildings:
    title: Намалюйте двадцять будівель
    description: 'Намалюйте де-небудь хоча б 20 будівель. Відкрийте свій редактор, знайдіть погано промальовану місцевість у селі чи промисловій зоні і обведіть будиночки. '
  coastline:
    title: Уточніть берегову лінію
    description: >-
        Майже всі берегові лінії імпортовані хтозна-коли із векторизованих знімків
        низької роздільної здатності. Ви запросто зможете покращити таку лінію. Додайте
        не менше 10 точок до об’єкту з теґом ''natural=coastline''.
  farmland:
    title: Намалюйте поле
    description: >-
        Знайдіть засіяне поле чи пасовище (наприклад, у центрі США чи в Україні) і
        додайте його на мапу з теґом [https://wiki.openstreetmap.org/wiki/Tag:landuse%3Dfarmland
        landuse=farmland].
  highway:
    title: Прокладіть дорогу
    description: Часто це перше, що люди роблять коли приєднуються до OpenStreetMap. Знайдіть на мапі відсутню дорогу і накресліть її.
  josm:
    title: Використайте редактор JOSM
    description: >-
        Встановіть редактор JOSM, якщо досі цього не зробили, і відредагуйте щось
        із його допомогою. Ми радимо намалювати кілька будівель:


        Завантажте ділянку мапи, додайте шар знімків, натисніть ''A'' і клацніть на
        кут будівлі. Потім двічі клацніть на сусідній кут, щоб вийшла лінія. Потім
        натисніть ''X'' і витисніть лінію в прямокутник. Нарешті, натисніть ''Alt+A'',
        щоб додати теґ ''building=yes''. Готово — надсилайте зміни.
  fix:
    title: Дрібна правка
    description: >-
        Коментарі до наборів змін важливі. Але не для вас сьогодні: змініть щось і
        впишіть ''fix'' у поле коментаря. Тільки ці три букви й усе.
  haiti:
    title: Побувайте на Гаїті
    description: >-
        У 2010 році за 25 кілометрів на захід від столиці Гаїті — Порт-о-пренс стався
        катастрофічний землетрус. Ця трагедія дала початок Гуманітарній команді картографів,
        завдяки якій з’явилася точна мапа столиці. Але не решти території країни:
        знайдіть відсутню будівлю в Гаїті і намалюйте її.
  improve_river:
    title: Уточніть річку
    description: >-
        Багато річок уже нанесено на мапу. От тільки їхні контури обводили за нечіткими
        супутниковими знімками. Тепер ви зможете виправити це: запускайте JOSM, вибирайте
        річку яка на вас дивиться, натискайте ''W'' і покращуйте її геометрію. Додайте
        не менше 10 точок до ''waterway=river''.
  lanes:
    title: Порахуйте смуги
    description: Знайдіть дорогу яка не має теґу ''lanes''. Підключіть детальні знімки для цієї місцевості й додайте до дороги кількість смуг руху.
  leaf_types:
    title: Посадіть два дерева
    description: >-
        Позначити дерево — це не просто додати до точки теґ ''natural=tree''. Ви маєте
        визначити його тип. Будь ласка, прочитайте ці вікі-сторінки: [https://wiki.openstreetmap.org/wiki/RU:Key:leaf_type
        leaf_type], [https://wiki.openstreetmap.org/wiki/RU:Key:leaf_cycle leaf_cycle],
        а потім додайте 2 дерева поряд із домом чи десь у знайомому місці.
  lit:
    title: Освітіть вулицю
  note:
    title: Закрийте нотатку
    description: Увімкніть нотатки на сайті OSM і знайдіть неопрацьовані нотатки, які ви зможете опрацювати. Виправте нотатку
  railway:
    title: Додайте залізничний шлях
    description: Залізницям приділяють менше уваги ніж автошляхам, але вони не менш важливі! Додайте на мапу залізничний шлях. Якщо ви не знаєте де це зробити, знайдіть якусь станцію і домалюйте там додаткові гілки.
  sidewalk:
    title: Додайте тротуар
    description: >-
        Тротуар — це пішохідна доріжка поряд із дорогою. Щоб пішохідні маршрути прокладалися
        краще, знайдіть дороги без позначеного тротуару, і намалюйте дві доріжки по
        обидва боки (як на знімку) з додатковим теґом ''footway=sidewalk''. Коли будете
        креслити пішохідний перехід, використайте теґи ''highway=footway'' і ''footway=crossing''.
  stream:
    title: Намалюйте струмок
    description: Річки нанесені на мапу майже всюди, а от непозначених струмків ще достобіса. Знайдіть струмок (не канаву), і додайте його.
  bridge:
    title: Додайте міст
    description: Багато доріг у сільській місцевості креслять похапцем, не піклуючись про перетини зі струмками й річками. Знайдіть місце де картограф забув розділити дорогу й позначити міст, і зробіть це замість нього.
  delete:
    title: Видалити!
    description: Легко натрапити на пусту ділянку мапи і додати туди кілька об’єктів. Але чи вийде у вас знайти що-небудь зайве? Видаліть 5 об’єктів — але тільки таких що застаріли або зайві.
  giveway:
    title: Дати дорогу
  gomap:
    title: Go Map!!!
  lamps:
    title: Додайте вуличні ліхтарі
    description: >-
        Надворі пітьма? Бачите ліхтарі на вулиці? Навряд, щоб їх хтось додав на мапу.
        Позначте хоча б два [https://wiki.openstreetmap.org/wiki/Tag:highway%3Dstreet_lamp
        вуличні ліхтарі].
  osmand:
    title: Використовуйте OsmAnd
  streetcomplete:
    title: Скористайтесь StreetComplete
    description: >-
        Якщо у вас iPhone, то вам не пощастило. Користувачам Android треба встановити
        застосунок [https://play.google.com/store/apps/details?id=de.westnordost.streetcomplete
        StreetComplete] і виконати там кілька завдань. Ви витратите лише кілька секунд.
  switch:
    description: >-
        У місці з’єднання двох залізничних шляхів установлений стрілковий перевід.
        Знайдіть станцію, і додайте щонайменше два теґи [https://wiki.openstreetmap.org/wiki/Tag:railway%3Dswitch
        railway=switch] до точок з’єднання шляхів.
  tracks:
    title: Додайте трохи путівців
    description: >-
        Путівці — це польові чи лісові дороги без твердого покриття. Їх позначають
        теґом [https://wiki.openstreetmap.org/wiki/Tag:highway%3Dtrack highway=track]
        із додатковим ''tracktype=gradeN'', де N набуває значень від 1 (найякісніше
        покриття) до 5 (найгірше покриття). Знайдіть на мапі поле чи ліс і накресліть
        2-3 кілометри такої дороги.
  turn_restriction:
    title: Додайте заборону повороту
    description: Знайдіть відсутню заборону маневру з допомогою Mapillary чи якогось іншого доступного для OSM джерела даних. Зробіть це в невеличкому містечку, якщо хочете. Позначте заборону.
  turnlanes:
    title: Рух по смугах
    description: >-
        Прочитайте опис [https://wiki.openstreetmap.org/wiki/Key:turn#Turning_indications_per_lane
        turn:lanes], знайдіть перехрестя із розміткою на супутникових знімках чи в
        Mapillary, і позначте усі смуги поворотів на усіх (зазвичай, чотирьох) дорогах
        перехрестя.
  waste_basket:
    title: Сміттєві контейнери
    description: >-
        Коли ви десь гуляєте, то бачите багато сміттєвих контейнерів: поряд із магазинами,
        на зупинках, біля входів до будівель. Згадайте такий контейнер і позначте
        його теґом ''amenity=waste_basket''.
  bench:
    title: Нанесіть лавку
    description: Пам’ятаєте як прогулювалися в парку? Здається, там були лавки? Згадайте де вони були, тому що в цьому завданні вам треба буде нанести на мапу хоча б одну.
  hot_task:
    title: Вирівняйте будівлі
    description: >-
        Відкрийте [https://tasks.hotosm.org/ HOT Tasking Manager] і виберіть будь-яке
        доступне завдання. Потім оберіть випадковий жовтий квадратик і перевірте його.
        Прослідкуйте, як новачки обводять будівлі. Відчуйте, як зростає ентропія.
        А потім виправте помилки: вирівняйте кути, скоригуйте форму. Кількох хатинок
        буде достатньо.
  postcode:
    title: Додайте поштовий індекс
    description: У деяких країнах, таких як Україна чи США, ви можете знайти поштовий індекс у публічних базах даних. У інших країнах ви або його знаєте, або вам доведеться шукати його деінде, наприклад на веб-сайті крамниці. Знайдіть поштовий індекс для якоїсь будівлі й укажіть його.
  subway:
    title: Полагодьте метро
    description: >-
        Якщо ви мастак на всякі штуки, ознайомтесь із [https://wiki.openstreetmap.org/wiki/Proposed_features/Metro_Mapping
        Public Transport v2 schema]. Відкрийте [https://osmz.ru/subways/ Subway Validator]
        і оберіть місто, в якому знайшлися помилки. Виправлення повинне зачепити маршрути
        метрополітену. Виправте — і можете йти, або ж продовжуйте прибирати помилки
        мережі метрополітенів.
  tiger:
    title: Причепуріть Tiger
    description: >-
        [https://wiki.openstreetmap.org/wiki/TIGER TIGER] — це публічний набір даних
        про дороги у США. Його імпортували в 2005, і цей імпорт був не ідеальним.
        Знайдіть дороги з ''tiger:reviewed=no'' і виправте хоча б три з них. Укажіть
        правильний клас дороги й приберіть теґ ''tiger:reviewed=no''.
